package analizador;

public enum Tokens
{
	SUMA, RESTA, MULTIPLICACION, DIVISION, POTENCIA, ERROR,TELEFONO, NUMERO,VALIDO,SEPARADOR, IDENTIFICADOR, MATRICULA, PRIMERA_ULTIMA_MINUSCULA, PALABRAS_RESERVADAS;
}